# Generated by Django 5.2.1 on 2025-05-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_iom_marcas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iom_marcas',
            table='iom_marcas',
        ),
    ]
