# Generated by Django 5.2.1 on 2025-05-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_estatus_hilos_personal_ordenfabricacionenc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordenfabricacionenc',
            table='iom_orden_fabricacion_enc',
        ),
    ]
