# Generated by Django 5.2.1 on 2025-05-27 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_ordenfabricacionenc_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenfabricacionenc',
            old_name='id_orden_fabricacion_enc',
            new_name='id_orden_fabricacion',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='id',
        ),
        migrations.AddField(
            model_name='personal',
            name='id_personal',
            field=models.AutoField(db_column='id_personal', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordenfabricacionenc',
            name='id_armador',
            field=models.ForeignKey(db_column='id_armador', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_armador', to='tasks.personal'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacionenc',
            name='id_cortador',
            field=models.ForeignKey(db_column='id_cortador', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_cortador', to='tasks.personal'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacionenc',
            name='id_empacador',
            field=models.ForeignKey(db_column='id_empacador', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_empacador', to='tasks.personal'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacionenc',
            name='id_estatus',
            field=models.ForeignKey(db_column='id_estatus', on_delete=django.db.models.deletion.PROTECT, to='tasks.estatus'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacionenc',
            name='id_hilos',
            field=models.ForeignKey(db_column='id_hilos', on_delete=django.db.models.deletion.PROTECT, to='tasks.hilos'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacionenc',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.PROTECT, to='tasks.sucursal'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacionenc',
            name='id_vendedor',
            field=models.ForeignKey(db_column='id_vendedor', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_vendedor', to='tasks.personal'),
        ),
    ]
