# Generated by Django 5.2.1 on 2025-05-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_id_orden_fabricacion_enc_ordenfabricacionenc_id_orden_fabricacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='apellido',
            new_name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='estatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hilos',
            name='id',
        ),
        migrations.AddField(
            model_name='estatus',
            name='id_estatus',
            field=models.AutoField(db_column='id_estatus', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='hilos',
            name='id_hilos',
            field=models.AutoField(db_column='id_hilos', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='cortador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordenfabricacionenc',
            name='id_orden_fabricacion',
            field=models.AutoField(db_column='id_orden_fabricacion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.AutoField(db_column='id_sucursal', primary_key=True, serialize=False),
        ),
    ]
