# Generated by Django 5.2.1 on 2025-05-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_apellido_personal_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='armador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='empacador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal',
            name='vendedor',
            field=models.BooleanField(default=False),
        ),
    ]
